"""empty message

Revision ID: 6728783d10e0
Revises: b86f0c331009
Create Date: 2020-02-11 08:04:28.286381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6728783d10e0'
down_revision = 'b86f0c331009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('user_stories', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'user_stories')
    # ### end Alembic commands ###
